In [1]:
#numpy can be used for numerical arrays and random number
import numpy as np
rng = np.random.default_rng()

In [2]:
rng.random()  


0.9143589809837429

In [5]:
rng.standard_normal(10)  

array([ 1.02549446,  1.29767199, -0.59631364, -0.96919755, -1.71076189,
       -0.06932538, -0.32509312, -0.92354585,  1.21798385,  0.01446221])

In [8]:
rng.integers(low=0, high=100, size=50) 

array([44, 45, 77,  3, 18, 91, 69, 79, 70, 34, 84, 41, 19, 78, 97, 49, 53,
       79, 49, 41, 83, 27, 62, 95,  5, 50, 82,  1, 25, 95, 96, 19, 80, 83,
        4, 67, 39,  1, 87, 77, 52, 75, 83, 66, 10, 70, 61, 64, 48, 21],
      dtype=int64)

In [ ]:
rng = np.random.default_rng()
# Generate one random float uniformly distributed over the range [0, 1)
rng.random()  
0.06369197489564249  # may vary
# Generate an array of 10 numbers according to a unit Gaussian distribution.
rng.standard_normal(10)  
array([-0.31018314, -1.8922078 , -0.3628523 , -0.63526532,  0.43181166,  # may vary
        0.51640373,  1.25693945,  0.07779185,  0.84090247, -2.13406828])
# Generate an array of 5 integers uniformly over the range [0, 10).
rng.integers(low=0, high=10, size=5)  
array([8, 7, 6, 2, 0])  # may vary