In [1]:
#numpy can be used for numerical arrays and random number
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
rng = np.random.default_rng()

In [2]:
penguin = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv")
print (penguin.to_string())

       species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g     sex
0       Adelie  Torgersen            39.1           18.7              181.0       3750.0    MALE
1       Adelie  Torgersen            39.5           17.4              186.0       3800.0  FEMALE
2       Adelie  Torgersen            40.3           18.0              195.0       3250.0  FEMALE
3       Adelie  Torgersen             NaN            NaN                NaN          NaN     NaN
4       Adelie  Torgersen            36.7           19.3              193.0       3450.0  FEMALE
5       Adelie  Torgersen            39.3           20.6              190.0       3650.0    MALE
6       Adelie  Torgersen            38.9           17.8              181.0       3625.0  FEMALE
7       Adelie  Torgersen            39.2           19.6              195.0       4675.0    MALE
8       Adelie  Torgersen            34.1           18.1              193.0       3475.0     NaN
9       Adelie  Torgersen     

In [3]:
print (penguin.to_string())

       species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g     sex
0       Adelie  Torgersen            39.1           18.7              181.0       3750.0    MALE
1       Adelie  Torgersen            39.5           17.4              186.0       3800.0  FEMALE
2       Adelie  Torgersen            40.3           18.0              195.0       3250.0  FEMALE
3       Adelie  Torgersen             NaN            NaN                NaN          NaN     NaN
4       Adelie  Torgersen            36.7           19.3              193.0       3450.0  FEMALE
5       Adelie  Torgersen            39.3           20.6              190.0       3650.0    MALE
6       Adelie  Torgersen            38.9           17.8              181.0       3625.0  FEMALE
7       Adelie  Torgersen            39.2           19.6              195.0       4675.0    MALE
8       Adelie  Torgersen            34.1           18.1              193.0       3475.0     NaN
9       Adelie  Torgersen     

In [4]:
rng.random()  


0.03327305604824149

In [5]:
rng.standard_normal(10)  

array([ 0.72793828, -0.62273251, -0.41324866,  0.05461902,  0.74800726,
       -0.18062363,  0.67220995,  0.29706452, -0.2475153 ,  1.5590884 ])

In [6]:
rng.integers(low=0, high=100, size=50) 

array([ 1, 22, 22, 11, 62, 33, 17, 78, 21, 97, 75, 38, 22, 98, 13, 64,  3,
       79, 82, 13, 84, 84, 12, 80, 99, 12, 64, 13, 83, 13, 11, 54, 25, 29,
       14, 36, 34, 80, 88, 52, 30, 27, 83, 17,  0, 40, 48, 33,  4, 48],
      dtype=int64)

In [7]:
rng = np.random.default_rng()
# Generate one random float uniformly distributed over the range [0, 1)
rng.random()  
0.06369197489564249  # may vary
# Generate an array of 10 numbers according to a unit Gaussian distribution.
rng.standard_normal(10)  
array([-0.31018314, -1.8922078 , -0.3628523 , -0.63526532,  0.43181166,  # may vary
        0.51640373,  1.25693945,  0.07779185,  0.84090247, -2.13406828])
# Generate an array of 5 integers uniformly over the range [0, 10).
rng.integers(low=0, high=10, size=5)  
array([8, 7, 6, 2, 0])  # may vary

NameError: name 'array' is not defined