In [3]:
#numpy can be used for numerical arrays and random number
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
rng = np.random.default_rng()

In [4]:
penguin = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv")
print (penguin.to_string())

       species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g     sex
0       Adelie  Torgersen            39.1           18.7              181.0       3750.0    MALE
1       Adelie  Torgersen            39.5           17.4              186.0       3800.0  FEMALE
2       Adelie  Torgersen            40.3           18.0              195.0       3250.0  FEMALE
3       Adelie  Torgersen             NaN            NaN                NaN          NaN     NaN
4       Adelie  Torgersen            36.7           19.3              193.0       3450.0  FEMALE
5       Adelie  Torgersen            39.3           20.6              190.0       3650.0    MALE
6       Adelie  Torgersen            38.9           17.8              181.0       3625.0  FEMALE
7       Adelie  Torgersen            39.2           19.6              195.0       4675.0    MALE
8       Adelie  Torgersen            34.1           18.1              193.0       3475.0     NaN
9       Adelie  Torgersen     

In [5]:
print (penguin.to_string())

       species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g     sex
0       Adelie  Torgersen            39.1           18.7              181.0       3750.0    MALE
1       Adelie  Torgersen            39.5           17.4              186.0       3800.0  FEMALE
2       Adelie  Torgersen            40.3           18.0              195.0       3250.0  FEMALE
3       Adelie  Torgersen             NaN            NaN                NaN          NaN     NaN
4       Adelie  Torgersen            36.7           19.3              193.0       3450.0  FEMALE
5       Adelie  Torgersen            39.3           20.6              190.0       3650.0    MALE
6       Adelie  Torgersen            38.9           17.8              181.0       3625.0  FEMALE
7       Adelie  Torgersen            39.2           19.6              195.0       4675.0    MALE
8       Adelie  Torgersen            34.1           18.1              193.0       3475.0     NaN
9       Adelie  Torgersen     

In [6]:
rng.random()  


0.5050773953234968

In [7]:
rng.standard_normal(10)  

array([ 0.32586386,  0.25171216, -1.35016326, -0.04604711,  0.0221948 ,
       -1.4265978 ,  0.45081116, -0.20824767, -1.08409573, -1.3111599 ])

In [8]:
rng.integers(low=0, high=100, size=50) 

array([37, 20, 27, 79, 87, 40, 98, 93, 54, 33, 12, 57, 99, 12, 57, 78, 75,
       55, 74, 78, 11, 86, 98, 65, 72, 33, 44, 36, 86, 79, 44, 94, 75, 35,
       14, 64, 49, 84, 61, 95, 75, 95, 26, 47, 38, 87, 98, 60, 77, 94],
      dtype=int64)

In [9]:
rng = np.random.default_rng()
# Generate one random float uniformly distributed over the range [0, 1)
rng.random()  
0.06369197489564249  # may vary
# Generate an array of 10 numbers according to a unit Gaussian distribution.
rng.standard_normal(10)  
array([-0.31018314, -1.8922078 , -0.3628523 , -0.63526532,  0.43181166,  # may vary
        0.51640373,  1.25693945,  0.07779185,  0.84090247, -2.13406828])
# Generate an array of 5 integers uniformly over the range [0, 10).
rng.integers(low=0, high=10, size=5)  
array([8, 7, 6, 2, 0])  # may vary

NameError: name 'array' is not defined

In [10]:
# Create subplots
fig, ax = plt.subplots(2, 2, figsize=(15, 8))
fig.suptitle('Palmer Penguins Dataset Combination of Violin and Swarm plots')

# Plotting
sns.violinplot(data=penguin, x='species', y='bill_length_mm', hue='sex', ax=ax[0, 0], size = 3, inner='quartile')
sns.swarmplot(data=penguin, x='species', y='bill_length_mm', hue='sex', ax=ax[0, 0], size = 3, dodge=True)

sns.violinplot(data=penguin, x='species', y='bill_depth_mm', hue='sex', ax=ax[0, 1], inner='quartile')
sns.swarmplot(data=penguin, x='species', y='bill_depth_mm', hue='sex', ax=ax[0, 1], dodge=True)

sns.violinplot(data=penguin, x='species', y='flipper_length_mm', hue='sex', ax=ax[1, 0], inner='quartile')
sns.swarmplot(data=penguin, x='species', y='flipper_length_mm', hue='sex', ax=ax[1, 0], dodge=True)

sns.violinplot(data=penguin, x='species', y='body_mass_g', hue='sex', ax=ax[1, 1], inner='quartile')
sns.swarmplot(data=penguin, x='species', y='body_mass_g', hue='sex', ax=ax[1, 1], dodge=True)

<Axes: xlabel='species', ylabel='body_mass_g'>